# Generated by Django 4.2.19 on 2025-03-12 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_payee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payee',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='name',
        ),
        migrations.AddField(
            model_name='payee',
            name='payee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_payee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
